title: Ray Lin
logo: "/images/bio_photo.png?raw=true" # your photo (or logo) here
description: >
  Software Developer, LLM, Data Science
  <br>
  Programming Languages: C# (.net core / webform), Python, JavaScript, R
  <br>
  Database: Sql Server, Redis, MongoDB (Atlas Search)
  <br>
  MQ: RabbitMQ, Azure Service Bus, Kafka
  <br>
  Cloud: Azure, AWS
  <br>
  Tools: Docker, GIT, Alteryx, Figma, Power Automate, Copilot Studio
  <br>
  BI Tools: Power BI, Tableau
  <br>
  ERP Software: SAP (Hana), SAS EM
  <br>
  <br>
  
theme: jekyll-theme-minimal
