title: Ray Lin
logo: "/images/bio.jpg?raw=true" # your photo (or logo) here
description: >
  Software Developer, Supply Chain Management/Optimization, LLM, Data Analytics/Science, Discrete Event Simulation
  <br>
  Programming Languages: C# (.net core mvc / .net framework webform/winform), Python, JavaScript, R, typescript
  <br>
  Database: Sql (Sql Server, MySql), Redis (RediSearch), MongoDB (Atlas Search)
  <br>
  MQ: RabbitMQ, Azure Service Bus, Kafka
  <br>
  Cloud: Azure, AWS, GCP 
  <br>
  Tools: Docker, Kubernetes (GKE), GIT, Alteryx, Figma, Power Automate, Copilot Studio, Gurobi, Airflow, GraphQL
  <br>
  BI Tools: Power BI, Tableau, Looker
  <br>
  ERP Software: SAP (Hana), SAS EM
  <br>
  
theme: jekyll-theme-minimal
