title: Ray Lin
logo: "/images/bio_photo.png?raw=true" # your photo (or logo) here
description: >
  Software Developer, Sql, C#, Data Scientist 
  <br>
  <br>
  <a href="https://www.linkedin.com/in/larrychencpa/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
