title: Ray Lin
logo: "/images/bio_photo.png?raw=true" # your photo (or logo) here
description: >
  Software Developer, LLM, Data Science
  Programming Languages: C#, Python, JavaScript
  Database: Sql Server, Redis, MongoDB
  Message Queue: RabbitMQ, Azure Service Bus, Kafka
  Cloud: Azure, AWS
  <br>
  <br>
  
theme: jekyll-theme-minimal
