title: Ray Lin
logo: "/images/bio_photo.png?raw=true" # your photo (or logo) here
description: >
  Software Developer, LLM, Data Science
  <br>
  Programming Languages: C# (.net), Python, JavaScript, R
  <br>
  Database: Sql Server, Redis, MongoDB
  <br>
  MQ: RabbitMQ, Azure Service Bus, Kafka
  <br>
  Cloud: Azure, AWS
  <br>
  Tools: Docker, GIT, Alteryx
  <br>
  BI Tools: Power BI, Tableau
  <br>
  ERP Software: SAP, SAS EM
  <br>
  <br>
  
theme: jekyll-theme-minimal
