title: Ray Lin
logo: "/images/bio_photo.png?raw=true" # your photo (or logo) here
description: >
  Software Developer, Supply Chain Management, LLM, Data Analytics/Science, Optimization
  <br>
  Programming Languages: C# (.net core mvc / .net framework webform/winform), Python, JavaScript, R
  <br>
  Database: Sql Server, Redis (RediSearch), MongoDB (Atlas Search)
  <br>
  MQ: RabbitMQ, Azure Service Bus, Kafka
  <br>
  Cloud: Azure, AWS, GCP
  <br>
  Tools: Docker, GIT, Alteryx, Figma, Power Automate, Copilot Studio
  <br>
  BI Tools: Power BI, Tableau
  <br>
  ERP Software: SAP (Hana), SAS EM
  <br>
  <br>
  
theme: jekyll-theme-minimal
