title: Larry Chen
logo: "/images/bio_photo.png?raw=true" # your photo (or logo) here
description: >
  Data Scientist, CPA, and Ramen Lover. 
  <br>
  <br>
  <a href="https://www.linkedin.com/in/larrychencpa/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
